### ISSUE TITLE
Fix behavior and integrate the search field

### ISSUE THREAD

**Issue by victorcabral182** [victorcabral182/coin_gecko_clone#2]
![image](https://github.com/victorcabral182/coin_gecko_clone/assets/107046713/86b85f88-a251-42b1-8a7a-4525e77119fd)

**Comment by victorcabral182** [comment]
PENDING: Fix behavior.

**Comment by vishalyadav98** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
Amarahadi, @Lostfunds, @Sadam99ali, @braveheartcc33, @ujerry582, @M-Sayeh, @Terrapind, @rango007, @Fleksr7913, @jmrrvagp, @panoramic-pandorum-intelpayportal-art, @S3OUDYY, @Civil0631, @Riyadhusen, @munnaislamb, @Gazzuye12, @imdsahin2, @Yham2301, @AnderGoig, @jaskaran-online, @YATTCHIEM, @0xKafi, @hpk1993, @Khanchai59, @SimmonsServices41, @cornbread78, @LocalLegend517, @Asusani, @candra1107, @Mehdi207-mp, @TST539996, @Raheelsaleem126, @amigp3, @Amrit247, @wangyanchang21, @miaoimiao, @mongoloidkhulmikuki366385, @amumubuku, @ThuThu12, @Bishoponome, @onegirlanna87, @jazzy182, @My178-oss, @Mr-Shery026, @Ankordara, @frazierjoh, @Alshaib2222, @seekersoftec, @Kosratsheikh, @Hautruong83Philetrs, @Huncho3511, @Billiej88, @darkus69, @Rizal387, @greyk4201, @Somir08, @Doganozturk57, @lil-fahad, @pantaovay, @IceEFresh, @Atefe6, @kzml2850, @quinthaz, @robertosiga, @EYEFOUREYE, @shayro77, @drjohn001, @jayb1027, @lacvinhky, @Masbrowedi, @R101-c, @MMC-MMCOIN, @Mhiztajapo, @history-62, @fahadlahmd, @Mhdeyb97, @haroldgallardo27, @Gustavobsbs, @Rapheal36998, @Laffy3080, @133Tommy321, @Khanchai59, @farisei77, @Luu9987, @Numandrsn25, @lukeb36, @manny363, @Goldmerc78, @YoungD2023, @Arashmgbrj, @Amlplots, @atus42, @Abubakarsidi, @andresrodzr, @IBRAHIM-1453, @Emadami, @remembermeLiu, @mkshariif, @Saeedafr

**Comment by Gazzuye12** [comment]
Hi

**Comment by Gazzuye12** [comment]
Hi
